version: 1
requiredStatusChecks:
  - pr (ubuntu-24.04)
  - pr (ubuntu-24.04-arm)
  - pr (macos-26)
  - pr (windows-2025)
  - pr (windows-11-arm)
settings:
  description: About View for LVCE Editor
  homepage: https://lvce-editor.github.io/about-view/
topics:
  - about
  - editor
  - lvce-editor
labels:
  - name: repository-config
    color: '5319e7'
    description: Changes to GitHub repository configuration
milestones: []
branches:
  - name: main
    protection:
      enforce_admins: true
      required_signatures: false
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        require_last_push_approval: false
